---
abstract: 'Teng-specific producer for SQL::Translator'
author:
  - 'Songmu <y.songmu@gmail.com>'
build_requires:
  File::Temp: 0
  Test::More: 0.98
  Test::Requires: 0
  parent: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.0, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Translator-Producer-Teng
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  SQL::Translator::Producer::Teng:
    file: lib/SQL/Translator/Producer/Teng.pm
    version: 0.02
requires:
  DBI: 0
  Data::Section::Simple: 0
  SQL::Translator: 0.11017
  Text::Xslate: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/Songmu/p5-SQL-Translator-Producer-Teng/issues
  homepage: https://github.com/Songmu/p5-SQL-Translator-Producer-Teng
  repository: git://github.com/Songmu/p5-SQL-Translator-Producer-Teng.git
version: 0.02
